name: Gradle Publish

on:
  release:
    types:
      - published

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Gradle Build
        run: ./gradlew getVersion -PreleaseVersion=$GITHUB_REF_NAME --info
